-- MySQL Script generated by MySQL Workbench
-- Wed Oct 14 18:36:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `nom` INT NULL,
  `carrer` VARCHAR(512) NULL,
  `numero` INT NULL,
  `pis` INT NULL,
  `porta` VARCHAR(45) NULL,
  `citat` VARCHAR(45) NULL,
  `codi_postal` CHAR(5) NULL,
  `pais` VARCHAR(45) NULL,
  `telefon` INT NULL,
  `fax` INT NULL,
  `nif` CHAR(9) NULL,
  PRIMARY KEY (`nom`),
  UNIQUE INDEX `telefon_UNIQUE` (`telefon` ASC) VISIBLE,
  UNIQUE INDEX `fax_UNIQUE` (`fax` ASC) VISIBLE,
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `id_client` INT NULL,
  `nom` VARCHAR(512) NULL,
  `adreça` VARCHAR(512) NULL,
  `telefon` INT NULL,
  `email` VARCHAR(512) NULL,
  `registre` DATE NULL,
  `Customer_id_client` INT NOT NULL,
  PRIMARY KEY (`id_client`, `Customer_id_client`),
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC) VISIBLE,
  UNIQUE INDEX `telefon_UNIQUE` (`telefon` ASC) VISIBLE,
  INDEX `fk_Customer_Customer1_idx` (`Customer_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Customer1`
    FOREIGN KEY (`Customer_id_client`)
    REFERENCES `mydb`.`Customer` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Worker` (
  `id_empleat` INT NULL,
  `nom` VARCHAR(512) NULL,
  PRIMARY KEY (`id_empleat`),
  UNIQUE INDEX `id_empleat_UNIQUE` (`id_empleat` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Glasses` (
  `marca` INT NULL,
  `graduacio_d` DECIMAL(2) NULL,
  `graduacio_i` DECIMAL(2) NULL,
  `muntura_tipo` ENUM('flotant', 'pasta', 'metallica') NULL,
  `muntura_color` VARCHAR(45) NULL,
  `vidrio_d_color` VARCHAR(45) NULL,
  `vidrio_i_color` VARCHAR(45) NULL,
  `preu` DECIMAL UNSIGNED NULL,
  `Supplier_nom` INT NOT NULL,
  `Customer_id_client` INT NOT NULL,
  `Worker_id_empleat` INT NOT NULL,
  PRIMARY KEY (`marca`),
  INDEX `fk_Glasses_Supplier_idx` (`Supplier_nom` ASC) VISIBLE,
  INDEX `fk_Glasses_Customer1_idx` (`Customer_id_client` ASC) VISIBLE,
  INDEX `fk_Glasses_Worker1_idx` (`Worker_id_empleat` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Supplier`
    FOREIGN KEY (`Supplier_nom`)
    REFERENCES `mydb`.`Supplier` (`nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Customer1`
    FOREIGN KEY (`Customer_id_client`)
    REFERENCES `mydb`.`Customer` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Worker1`
    FOREIGN KEY (`Worker_id_empleat`)
    REFERENCES `mydb`.`Worker` (`id_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
